FROM python:3.10

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY config/requirements.txt config/
RUN pip install --no-cache-dir -r config/requirements.txt

COPY alembic.ini .
COPY server server

CMD alembic upgrade head && uvicorn server.main:app --host 0.0.0.0 --reload
